[opener]
nvim = [
  { run = 'nvim %s', block = true, desc = "nvim" },
]
vscode = [
  { run = 'code %s', desc = "code", orphan = true },
]

[open]
rules = [
  { url = "*", use = ["nvim", "vscode"] },
]

[mgr]
show_hidden = true
