# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sainnhe/tmux-fzf'

# clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# copy mode
bind i copy-mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# mouse
set -g mouse on

# prefix
set -g prefix C-q

# panes
setw -g pane-base-index 1
bind ] rotate-window -D
bind [ rotate-window -U
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# sessions
set -g base-index 1
bind-key "s" run-shell -b "${HOME}/.tmux/plugins/tmux-fzf/scripts/session.sh switch"

# reload
bind r source-file ~/.tmux.conf \; display-message "Reloaded"

# status bar
set -g status-interval 1 
set -g status-left '[#{session_name}]:#{window_index}-#{pane_index} '
set -g status-left-length 50
set -g window-status-format ''
set -g window-status-current-format ''
set -g status-right '#{pane_current_path} #(cd "#{pane_current_path}" && branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) && [ -n "$branch" ] && echo "($branch)")'
set -g status-right-length 200


# windows
bind \\ split-window -h
bind - split-window -v
bind-key "w" run-shell -b "${HOME}/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

# tpm
run '~/.tmux/plugins/tpm/tpm'
